version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: minha_api
    ports:
      - "3030:3030"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/produtosdb

volumes:
  mongo_data: